In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sqlalchemy as sql
#!pip install pymysql

driver = sql.create_engine('mysql+pymysql://guest:ctu-relational@relational.fel.cvut.cz:3306/financial')

Using **pandas** and **SQLAlchemy**, we query the relational database to compute descriptive statistics by joining multiple tables. This approach allows us to aggregate information across related entities and extract meaningful insights from the database structure.

## Average of payments per district

In [9]:
query = """
SELECT d.A2 AS district_name, AVG(l.payments) AS avg_payments
FROM loan l
JOIN account a ON l.account_id = a.account_id
JOIN district d ON a.district_id = d.district_id
GROUP BY d.district_id
ORDER BY avg_payments DESC
"""

df_avg_payments = pd.read_sql(query, driver)
df_avg_payments.head()

      district_name  avg_payments
0  Zdar nad Sazavou   6750.428571
1         Domazlice   6461.000000
2           Jesenik   6357.000000
3           Bruntal   5964.166667
4            Nachod   5878.333333

## Active loans per district

In [10]:
query = """
SELECT d.A2 AS district_name, COUNT(*) AS active_loans
FROM loan l
JOIN account a ON l.account_id = a.account_id
JOIN district d ON a.district_id = d.district_id
WHERE l.status = 'A'
GROUP BY d.district_id
ORDER BY active_loans DESC
"""

df_active_loans = pd.read_sql(query, driver)
df_active_loans.head()

     district_name  active_loans
0      Hl.m. Praha            34
1          Karvina             9
2  Frydek - Mistek             7
3             Zlin             6
4  Ostrava - mesto             6

## Total orders and average of loan amounts per district

In [11]:
query = """
SELECT d.A2 AS district_name,
       COUNT(o.order_id) AS total_orders,
       AVG(o.amount) AS avg_order_amount
FROM `order` o
JOIN account a ON o.account_id = a.account_id
JOIN district d ON a.district_id = d.district_id
GROUP BY d.district_id
ORDER BY total_orders DESC
"""

df_orders = pd.read_sql(query, driver)
df_orders.head()

     district_name  total_orders  avg_order_amount
0      Hl.m. Praha           816        3400.57145
1          Karvina           216        3118.84815
2  Ostrava - mesto           203        3165.30936
3     Brno - mesto           178        3284.52303
4  Frydek - Mistek           132        3612.62879

## Average balance per district (using the last transaction)

This query requires a subquery to extract the last transaction for every count.

In [12]:
query = """
SELECT d.A2 AS district_name, AVG(t.balance) AS avg_latest_balance
FROM (
    SELECT t1.account_id, t1.balance
    FROM trans t1
    INNER JOIN (
        SELECT account_id, MAX(date) AS max_date
        FROM trans
        GROUP BY account_id
    ) t2 ON t1.account_id = t2.account_id AND t1.date = t2.max_date
) t
JOIN account a ON t.account_id = a.account_id
JOIN district d ON a.district_id = d.district_id
GROUP BY d.district_id
ORDER BY avg_latest_balance DESC
"""

df_balances = pd.read_sql(query, driver)
df_balances.head()

     district_name  avg_latest_balance
0  Usti nad Orlici          57293.8983
1          Teplice          50519.5652
2          Blansko          49001.5686
3           Vyskov          48920.5294
4          Nymburk          48609.8163

## Count of accounts per district

In [13]:
query = """
SELECT d.A2 AS district_name, COUNT(a.account_id) AS num_accounts
FROM account a
JOIN district d ON a.district_id = d.district_id
GROUP BY d.district_id
ORDER BY num_accounts DESC
"""

df_accounts = pd.read_sql(query, driver)
df_accounts.head()

     district_name  num_accounts
0      Hl.m. Praha           554
1          Karvina           152
2  Ostrava - mesto           135
3     Brno - mesto           128
4             Zlin            92

## Number of clients having at least one loan

In [14]:
query = """
SELECT COUNT(DISTINCT c.client_id) AS clients_with_loans
FROM loan l
JOIN account a ON l.account_id = a.account_id
JOIN disp dp ON a.account_id = dp.account_id AND dp.type = 'OWNER'
JOIN client c ON dp.client_id = c.client_id
"""

df_clients_loans = pd.read_sql(query, driver)
df_clients_loans.head()

   clients_with_loans
0                 682

## Average amount of loan per duration

In [15]:
query = """
SELECT duration, AVG(amount) AS avg_amount
FROM loan
GROUP BY duration
ORDER BY duration ASC
"""

df_loan_duration = pd.read_sql(query,driver)
df_loan_duration.head()

   duration   avg_amount
0        12   53635.5115
1        24   99217.9130
2        36  144048.1846
3        48  205592.6957
4        60  244450.7586

## Number of cards per type

In [16]:
query = """
SELECT type, COUNT(*) AS num_cards
FROM card
GROUP BY type
ORDER BY num_cards DESC
"""

df_card_types = pd.read_sql(query, driver)
df_card_types.head()

      type  num_cards
0  classic        659
1   junior        145
2     gold         88

## Accounts with most transactions

In [17]:
query = """
SELECT account_id, COUNT(*) AS num_transactions
FROM trans
GROUP BY account_id
ORDER BY num_transactions DESC
LIMIT 10
"""

df_top_trans_accounts = pd.read_sql(query, driver)
df_top_trans_accounts.head()

   account_id  num_transactions
0        8261               675
1        3834               665
2          96               661
3        2932               655
4        9307               649

## Total amount w.r.t the status of the loan

In [18]:
query = """
SELECT status, COUNT(*) AS num_loans, SUM(amount) AS total_amount
FROM loan
GROUP BY status
ORDER BY total_amount DESC
"""

df_loans_by_status = pd.read_sql(query, driver)
df_loans_by_status.head()

  status  num_loans  total_amount
0      C        403    69078372.0
1      A        203    18603216.0
2      D         45    11217804.0
3      B         31     4362348.0

## Average amount per type of operations

In [19]:
query = """
SELECT operation, COUNT(*) AS num_trans, AVG(amount) AS avg_amount
FROM trans
GROUP BY operation
ORDER BY avg_amount DESC
"""

df_trans_by_operation = pd.read_sql(query, driver)
df_trans_by_operation.head()

        operation  num_trans  avg_amount
0           VKLAD     156743  15429.8626
1   PREVOD Z UCTU      65226  11981.1111
2           VYBER     434918   5379.3374
3  PREVOD NA UCET     208283   3229.4450
4    VYBER KARTOU       8036   2261.1249

See the 01_eda.ipynb for the description of the operation types.

## Total orders per account

In [20]:
query = """
SELECT account_id, COUNT(*) AS num_orders, SUM(amount) AS total_ordered
FROM `order`
GROUP BY account_id
ORDER BY total_ordered DESC
LIMIT 10
"""

df_order_totals = pd.read_sql(query, driver)
df_order_totals.head()

   account_id  num_orders  total_ordered
0        3005           3        22704.3
1        2371           5        21785.3
2        2910           3        21725.3
3        1718           2        21634.0
4       10663           3        21322.2

## Number of accounts per release type

In [21]:
query = """
SELECT frequency, COUNT(*) AS count
FROM account
GROUP BY frequency
ORDER BY count DESC
"""

df_freq = pd.read_sql(query,driver)
df_freq.head()

            frequency  count
0    POPLATEK MESICNE   4167
1      POPLATEK TYDNE    240
2  POPLATEK PO OBRATU     93